name: POC React App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'

      - name: Install project NPM
        run: yarn

      - name: Build project
        run: yarn build
      
      - name: Run tests
        run: yarn test

      - name: Deploy project into Netlify
        uses: netlify/actions/cli@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true